# Generated by Django 5.2.6 on 2026-09-19 02:41

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("platform", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=60)),
                ("allow_decimal", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="units",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "unit",
                "verbose_name_plural": "units",
                "db_table": "inventory_unit",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("tenant", "code"),
                        name="uq_unit_tenant_code",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("tenant__isnull", True), ("deleted_at__isnull", True)),
                        fields=("code",),
                        name="uq_unit_system_code",
                    ),
                ],
            },
        ),
    ]
