# Generated by Django 5.2.6 on 2026-09-24 06:40

import apps.common.db.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_location"),
        # `ix_item_name_upper_trgm` needs `pg_trgm` (see tax 0002).
        ("common", "0001_enable_extensions"),
        ("platform", "0009_normalise_user_mobiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=60)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="children",
                        to="inventory.category",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "db_table": "inventory_category",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("goods", "Goods"), ("service", "Service")],
                        default="goods",
                        max_length=8,
                    ),
                ),
                ("sku", models.CharField(max_length=48)),
                ("barcode", models.CharField(blank=True, max_length=48, null=True)),
                ("hsn_sac", models.CharField(blank=True, max_length=8, null=True)),
                ("tax_code", models.CharField(default="GST0", max_length=16)),
                ("tax_inclusive_selling", models.BooleanField(default=False)),
                (
                    "purchase_price",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "selling_price",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "mrp",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("track_stock", models.BooleanField(default=True)),
                (
                    "reorder_point",
                    apps.common.db.fields.QuantityField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("image_attachment_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="items",
                        to="inventory.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="items",
                        to="inventory.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "db_table": "inventory_item",
            },
        ),
        migrations.CreateModel(
            name="ItemStock",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "on_hand",
                    apps.common.db.fields.QuantityField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "avg_cost",
                    apps.common.db.fields.UnitCostField(decimal_places=4, default=0, max_digits=14),
                ),
                ("last_movement_at", models.DateTimeField(blank=True, null=True)),
                ("last_sequence_no", models.IntegerField(default=0)),
                ("max_movement_date", models.DateField(blank=True, null=True)),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("ok", "Above reorder point"),
                            ("low", "At or below reorder point"),
                            ("out", "Out of stock"),
                        ],
                        default="ok",
                        max_length=8,
                    ),
                ),
                ("alert_level_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="stock_rows",
                        to="inventory.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="inventory.location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "item stock",
                "verbose_name_plural": "item stock",
                "db_table": "inventory_item_stock",
            },
        ),
        migrations.CreateModel(
            name="LowStockAlert",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("ok", "Above reorder point"),
                            ("low", "At or below reorder point"),
                            ("out", "Out of stock"),
                        ],
                        max_length=8,
                    ),
                ),
                ("on_hand", apps.common.db.fields.QuantityField(decimal_places=3, max_digits=14)),
                (
                    "reorder_point",
                    apps.common.db.fields.QuantityField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("movement", "A stock movement"),
                            ("reorder_edit", "A reorder-point edit"),
                            ("scan", "The nightly scan"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("sinks_delivered", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="inventory.location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "low-stock alert",
                "verbose_name_plural": "low-stock alerts",
                "db_table": "inventory_low_stock_alert",
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=32)),
                ("adjustment_date", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("damage", "Damage"),
                            ("theft", "Theft"),
                            ("count", "Count difference"),
                            ("personal_use", "Personal use"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("posted", "Posted")], default="posted", max_length=16
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="inventory.location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock adjustment",
                "verbose_name_plural": "stock adjustments",
                "db_table": "inventory_stock_adjustment",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence_no", models.IntegerField()),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening stock"),
                            ("purchase_in", "Purchase"),
                            ("sale_out", "Sale"),
                            ("sale_return_in", "Sale return"),
                            ("purchase_return_out", "Purchase return"),
                            ("adjust_in", "Adjustment +"),
                            ("adjust_out", "Adjustment −"),
                            ("transfer_in", "Transfer in"),
                            ("transfer_out", "Transfer out"),
                            ("stocktake_in", "Stock take +"),
                            ("stocktake_out", "Stock take −"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=24,
                    ),
                ),
                ("qty", apps.common.db.fields.QuantityField(decimal_places=3, max_digits=14)),
                (
                    "unit_cost",
                    apps.common.db.fields.UnitCostField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "avg_cost_after",
                    apps.common.db.fields.UnitCostField(decimal_places=4, max_digits=14),
                ),
                (
                    "on_hand_after",
                    apps.common.db.fields.QuantityField(decimal_places=3, max_digits=14),
                ),
                ("reason", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("item", "Item (opening stock)"),
                            ("stock_adjustment", "Stock adjustment"),
                            ("purchase_document", "Purchase document"),
                            ("sales_document", "Sales document"),
                            ("stock_transfer", "Stock transfer"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("movement_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="movements",
                        to="inventory.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="inventory.location",
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock movement",
                "verbose_name_plural": "stock movements",
                "db_table": "inventory_stock_movement",
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                models.F("tenant"),
                models.F("parent"),
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("deleted_at__isnull", True)),
                name="uq_category_sibling_name",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["tenant", "status", "name"], name="ix_item_tenant_status_name"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("name"), name="gin_trgm_ops"
                ),
                name="ix_item_name_upper_trgm",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["tenant", "category"], name="ix_item_tenant_category"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["tenant", "barcode"], name="ix_item_tenant_barcode"),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("tenant", "sku"),
                name="uq_item_tenant_sku",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode__isnull", False), ("deleted_at__isnull", True)),
                fields=("tenant", "barcode"),
                name="uq_item_tenant_barcode",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(("item_type", "goods"), ("track_stock", False), _connector="OR"),
                name="ck_item_service_untracked",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(("selling_price__gte", 0), ("purchase_price__gte", 0)),
                name="ck_item_prices_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemstock",
            constraint=models.UniqueConstraint(
                fields=("item", "location"), name="uq_item_stock_item_location"
            ),
        ),
        migrations.AddIndex(
            model_name="lowstockalert",
            index=models.Index(
                fields=["tenant", "item", "-created_at"], name="ix_low_stock_alert_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "number"), name="uq_adjustment_number"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant", "item", "location", "movement_date"], name="ix_movement_item_date"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant", "source_type", "source_id"], name="ix_movement_source"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["tenant", "movement_date"], name="ix_movement_tenant_date"),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty", 0), _negated=True), name="ck_movement_qty_nonzero"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.UniqueConstraint(
                fields=("item", "location", "sequence_no"), name="uq_movement_item_location_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("movement_type", "opening")),
                fields=("item", "location"),
                name="uq_movement_one_opening",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("movement_type", "reversal"), ("reverses__isnull", False)),
                    models.Q(("movement_type", "reversal"), _negated=True),
                    _connector="OR",
                ),
                name="ck_movement_reversal_has_source",
            ),
        ),
    ]
