# Generated by Django 5.2.6 on 2026-09-24 20:43

import apps.common.db.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0004_movement_forbid_update_delete"),
        ("parties", "0008_add_ordering_and_search_indexes_to_party"),
        ("platform", "0011_support_access_impersonation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("purchase_bill", "Purchase bill")],
                        default="purchase_bill",
                        max_length=16,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=32, null=True)),
                ("fy_label", models.CharField(max_length=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("recorded", "Recorded"),
                            ("partially_paid", "Partially paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("supplier_invoice_number", models.CharField(blank=True, max_length=48, null=True)),
                ("supplier_invoice_date", models.DateField(blank=True, null=True)),
                ("document_date", models.DateField()),
                ("due_on", models.DateField(blank=True, null=True)),
                ("place_of_supply_state", models.CharField(max_length=2)),
                ("is_inter_state", models.BooleanField(default=False)),
                ("reverse_charge", models.BooleanField(default=False)),
                ("itc_eligible", models.BooleanField(default=True)),
                ("supplier_gstin_snapshot", models.CharField(blank=True, max_length=15, null=True)),
                ("party_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "subtotal",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "Percent"), ("amount", "Amount")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "discount_value",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "discount_amount",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "taxable_total",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cgst_total",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "sgst_total",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "igst_total",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cess_total",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                ("round_off_enabled", models.BooleanField(default=True)),
                ("round_off", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "grand_total",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount_paid",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount_due",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=160, null=True)),
                ("version", models.IntegerField(default=1)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="purchase_documents",
                        to="parties.party",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase document",
                "verbose_name_plural": "purchase documents",
                "db_table": "purchases_document",
            },
        ),
        migrations.CreateModel(
            name="PurchaseDocumentLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("line_no", models.SmallIntegerField()),
                ("description", models.CharField(max_length=255)),
                ("hsn_sac", models.CharField(blank=True, max_length=8, null=True)),
                ("qty", apps.common.db.fields.QuantityField(decimal_places=3, max_digits=14)),
                ("unit_code", models.CharField(max_length=8)),
                (
                    "unit_cost",
                    apps.common.db.fields.UnitCostField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "Percent"), ("amount", "Amount")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "discount_value",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "discount_amount",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "taxable_value",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                ("tax_code", models.CharField(max_length=16)),
                (
                    "tax_rate",
                    apps.common.db.fields.RateField(decimal_places=3, default=0, max_digits=6),
                ),
                (
                    "cess_rate",
                    apps.common.db.fields.RateField(decimal_places=3, default=0, max_digits=6),
                ),
                (
                    "cgst",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "sgst",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "igst",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cess",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "line_total",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "inbound_unit_cost",
                    apps.common.db.fields.UnitCostField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchases.purchasedocument",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="purchase_lines",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase document line",
                "verbose_name_plural": "purchase document lines",
                "db_table": "purchases_document_line",
                "ordering": ["line_no"],
            },
        ),
        migrations.AddIndex(
            model_name="purchasedocument",
            index=models.Index(
                fields=["tenant", "kind", "status", "-document_date"],
                name="ix_purch_doc_kind_status",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasedocument",
            index=models.Index(
                fields=["tenant", "party", "-document_date"], name="ix_purch_doc_party"
            ),
        ),
        migrations.AddIndex(
            model_name="purchasedocument",
            index=models.Index(
                condition=models.Q(("status__in", ["recorded", "partially_paid"])),
                fields=["tenant", "due_on"],
                name="ix_purch_doc_open_due",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasedocument",
            index=models.Index(fields=["tenant", "number"], name="ix_purch_doc_number"),
        ),
        migrations.AddConstraint(
            model_name="purchasedocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number__isnull", False)),
                fields=("tenant", "kind", "fy_label", "number"),
                name="uq_purchases_document_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedocument",
            constraint=models.UniqueConstraint(
                models.F("tenant"),
                models.F("party"),
                django.db.models.functions.text.Upper("supplier_invoice_number"),
                condition=models.Q(
                    ("supplier_invoice_number__isnull", False),
                    models.Q(("status__in", ["void", "draft"]), _negated=True),
                ),
                name="uq_purchases_supplier_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("number__isnull", True), ("status", "draft")),
                    models.Q(
                        models.Q(("status", "draft"), _negated=True), ("number__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_purchases_document_number_iff_recorded",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("status", "draft"), ("party__isnull", False), _connector="OR"),
                name="ck_purchases_document_party_when_recorded",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paid__gte", 0), ("amount_due__gte", 0)),
                name="ck_purchases_document_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedocumentline",
            constraint=models.UniqueConstraint(
                fields=("document", "line_no"), name="uq_purchases_line_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedocumentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty__gt", 0)), name="ck_purchases_line_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasedocumentline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)),
                name="ck_purchases_line_cost_non_negative",
            ),
        ),
    ]
