# Generated by Django 5.2.6 on 2026-09-28 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0008_add_ordering_and_search_indexes_to_party"),
        ("platform", "0011_support_access_impersonation"),
        ("purchases", "0001_add_purchases_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="purchasedocument",
            index=models.Index(
                fields=["tenant", "-document_date", "-created_at", "-id"],
                name="ix_purch_doc_tenant_date",
            ),
        ),
    ]
