# Generated by Django 5.2.6 on 2026-09-24 06:38

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("platform", "0009_normalise_user_mobiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_type", models.CharField(max_length=48)),
                ("owner_id", models.UUIDField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("logo", "Logo"),
                            ("signature", "Signature"),
                            ("item_image", "Item image"),
                            ("bill_photo", "Bill photo"),
                            ("receipt", "Receipt"),
                            ("import_file", "Import file"),
                            ("export_file", "Export file"),
                            ("document_pdf", "Document PDF"),
                        ],
                        max_length=24,
                    ),
                ),
                ("storage_key", models.CharField(max_length=255, unique=True)),
                ("original_name", models.CharField(blank=True, default="", max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.BigIntegerField()),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("sha256", models.CharField(max_length=64)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
                "db_table": "files_attachment",
                "indexes": [
                    models.Index(
                        fields=["tenant", "owner_type", "owner_id"], name="ix_attachment_owner"
                    )
                ],
            },
        ),
    ]
