# Generated by Django 5.2.6 on 2026-09-19 06:08

import apps.common.db.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parties", "0001_initial"),
        ("platform", "0003_rate_limit_and_tenantless_idempotency"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("push", "Push"),
                        ],
                        max_length=16,
                    ),
                ),
                ("template_code", models.CharField(max_length=48)),
                ("to_address", models.CharField(max_length=254)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("provider", models.CharField(max_length=32)),
                ("provider_message_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("related_type", models.CharField(blank=True, max_length=48, null=True)),
                ("related_id", models.UUIDField(blank=True, null=True)),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="parties.party",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="message_logs",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "message log",
                "verbose_name_plural": "message logs",
                "db_table": "notifications_message_log",
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"], name="ix_message_log_tenant_created"
                    ),
                    models.Index(fields=["provider_message_id"], name="ix_message_log_provider_id"),
                ],
            },
        ),
    ]
