# Generated by Django 5.2.6 on 2026-09-24 06:40

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("platform", "0009_normalise_user_mobiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=48)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("push", "Push"),
                        ],
                        max_length=16,
                    ),
                ),
                ("locale", models.CharField(default="en", max_length=8)),
                ("body", models.TextField()),
                ("dlt_template_id", models.CharField(blank=True, max_length=32, null=True)),
                ("whatsapp_template_name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transactional", "Transactional"),
                            ("service_implicit", "Service implicit"),
                            ("service_explicit", "Service explicit"),
                            ("promotional", "Promotional"),
                        ],
                        default="service_implicit",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="platform.partner",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "message template",
                "verbose_name_plural": "message templates",
                "db_table": "notifications_template",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partner", "tenant", "code", "channel", "locale"),
                        name="uq_template_scope_code",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("money", "Money"),
                            ("stock", "Stock"),
                            ("reminders", "Reminders"),
                            ("team", "Team"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                        ],
                        default="info",
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.CharField(blank=True, default="", max_length=300)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("group_key", models.CharField(blank=True, max_length=80, null=True)),
                ("count", models.PositiveSmallIntegerField(default=1)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("read_by", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "notifications_notification",
                "indexes": [
                    models.Index(
                        fields=["tenant", "user", "read_at", "-created_at"],
                        name="ix_notification_inbox",
                    ),
                    models.Index(
                        fields=["tenant", "type", "group_key", "-created_at"],
                        name="ix_notification_group",
                    ),
                    models.Index(fields=["created_at"], name="ix_notification_created"),
                ],
            },
        ),
    ]
