import { screen, within } from '@testing-library/react';

import { renderWithProviders } from 'src/tests/renderWithProviders';

import { StatementPrintView, type StatementPrintViewProps } from './StatementPrintView';

/**
 * UAT D3 (Medium/P1) — the print sheet's letterhead.
 *
 * The printed statement named the shop and nothing else: no address, no phone,
 * no GSTIN. It is the page a merchant hands a customer who disputes a bill, and
 * a customer reading it should be able to tell who sent it and how to reach
 * them. `GET /tenants/current` carries all three; the sheet renders the ones a
 * merchant has filled in and prints NO line for the ones they have not — an
 * empty "GSTIN" line reads as a business that has not registered.
 */
const base: StatementPrintViewProps = {
  party: { id: 'p1', name: 'Ramesh Traders', mobileMasked: '98••• ••210' },
  period: { from: '2026-04-01', to: '2026-09-23' },
  summary: {
    openingBalance: '0.00',
    closingBalance: '1800.00',
    totalDebit: '2800.00',
    totalCredit: '1000.00',
    hasEntriesBeforeOpening: false,
  },
  rows: [],
  shopName: 'Kumar Kirana Store',
  generatedAt: '2026-09-24T10:00:00+05:30',
};

const letterhead = (): HTMLElement => screen.getByTestId('statement-letterhead');

describe('StatementPrintView letterhead (UAT D3)', () => {
  it("prints the shop's address, phone and GSTIN under its name", () => {
    renderWithProviders(
      <StatementPrintView
        {...base}
        shop={{
          addressLines: ['12 Station Road', 'Near Bus Stand', 'Nashik, Nashik 422001'],
          phone: '9822012345',
          gstin: '27ABCDE1234F1Z5',
        }}
      />
    );

    const head = within(letterhead());
    expect(head.getByText('Kumar Kirana Store')).toBeInTheDocument();
    expect(head.getByText('12 Station Road')).toBeInTheDocument();
    expect(head.getByText('Nashik, Nashik 422001')).toBeInTheDocument();
    expect(head.getByText('Phone 9822012345')).toBeInTheDocument();
    expect(head.getByText('GSTIN 27ABCDE1234F1Z5')).toBeInTheDocument();
  });

  it('prints no line at all for what the merchant has not filled in', () => {
    renderWithProviders(
      <StatementPrintView {...base} shop={{ addressLines: [], phone: '9822012345', gstin: null }} />
    );

    const head = within(letterhead());
    expect(head.getByText('Phone 9822012345')).toBeInTheDocument();
    expect(head.queryByText(/GSTIN/)).not.toBeInTheDocument();
  });

  it('still names the shop while the letterhead has not loaded', () => {
    renderWithProviders(<StatementPrintView {...base} shop={null} />);

    expect(within(letterhead()).getByText('Kumar Kirana Store')).toBeInTheDocument();
    expect(within(letterhead()).queryByText(/Phone|GSTIN/)).not.toBeInTheDocument();
  });

  it('keeps the "Generated by DigiKhaato" footer', () => {
    renderWithProviders(<StatementPrintView {...base} shop={null} />);
    expect(screen.getByText('Generated by DigiKhaato')).toBeInTheDocument();
  });
});
