# Generated by Django 5.2.6 on 2026-09-19 02:41

import apps.common.db.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("platform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HsnCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("default_tax_code", models.CharField(blank=True, default="", max_length=16)),
                ("is_service", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "HSN code",
                "verbose_name_plural": "HSN codes",
                "db_table": "tax_hsn",
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=40)),
                (
                    "rate",
                    apps.common.db.fields.RateField(decimal_places=3, default=0, max_digits=6),
                ),
                (
                    "cess_rate",
                    apps.common.db.fields.RateField(decimal_places=3, default=0, max_digits=6),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tax_rates",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "tax rate",
                "verbose_name_plural": "tax rates",
                "db_table": "tax_rate",
                "indexes": [
                    models.Index(fields=["code", "effective_from"], name="ix_tax_rate_lookup")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "code", "effective_from"), name="uq_tax_rate_code_from"
                    )
                ],
            },
        ),
    ]
