# Generated by Django 5.2.6 on 2026-09-24 06:40

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tax", "0001_initial"),
        # The GIN index needs `pg_trgm`; naming the migration that creates it
        # makes a rollback of `common` unapply this index first.
        ("common", "0001_enable_extensions"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hsncode",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("description"), name="gin_trgm_ops"
                ),
                name="ix_tax_hsn_description_trgm",
            ),
        ),
    ]
