# Generated by Django 5.2.6 on 2026-09-19 02:41

import apps.common.db.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_enable_extensions"),
        ("platform", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("display_code", models.CharField(blank=True, max_length=24, null=True)),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                ("alt_phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_customer", models.BooleanField(default=True)),
                ("is_supplier", models.BooleanField(default=False)),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "gst_registration",
                    models.CharField(
                        choices=[
                            ("unregistered", "Unregistered"),
                            ("regular", "Regular"),
                            ("composition", "Composition"),
                            ("overseas", "Overseas"),
                        ],
                        default="unregistered",
                        max_length=16,
                    ),
                ),
                ("billing_address", models.JSONField(blank=True, default=dict)),
                ("shipping_address", models.JSONField(blank=True, default=dict)),
                ("state_code", models.CharField(blank=True, max_length=2, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "balance",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "receivable_total",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "payable_total",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("collection_date", models.DateField(blank=True, null=True)),
                (
                    "credit_limit",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("credit_days", models.SmallIntegerField(blank=True, null=True)),
                ("sms_opt_in", models.BooleanField(default=True)),
                (
                    "consent_source",
                    models.CharField(
                        blank=True,
                        choices=[("verbal", "Verbal"), ("form", "Form"), ("link", "Link")],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "party",
                "verbose_name_plural": "parties",
                "db_table": "parties_party",
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "-last_activity_at"],
                        name="ix_party_tenant_activity",
                    ),
                    models.Index(fields=["tenant", "balance"], name="ix_party_tenant_balance"),
                    models.Index(
                        fields=["tenant", "collection_date"], name="ix_party_tenant_collection"
                    ),
                    models.Index(fields=["tenant", "is_customer"], name="ix_party_tenant_customer"),
                    models.Index(fields=["tenant", "is_supplier"], name="ix_party_tenant_supplier"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name"], name="ix_party_name_trgm", opclasses=["gin_trgm_ops"]
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("mobile__isnull", False), ("deleted_at__isnull", True)),
                        fields=("tenant", "mobile"),
                        name="uq_party_tenant_mobile",
                    )
                ],
            },
        ),
    ]
