# Generated by Django 5.2.6 on 2026-09-22 08:28

import apps.common.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0002_party_search_and_list_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="opening_balance_amount",
            field=apps.common.db.fields.MoneyField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="opening_balance_as_of",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="party",
            name="opening_balance_direction",
            field=models.CharField(
                blank=True,
                choices=[("debit", "They owe me"), ("credit", "I owe them")],
                max_length=6,
                null=True,
            ),
        ),
    ]
