# Generated by Django 5.2.6 on 2026-09-22 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Make the list's index match the list's ORDER BY, and drop the dead one.

    `ix_party_tenant_activity` was declared `-last_activity_at`, which is
    `DESC NULLS FIRST` in Postgres, while the query asks for `DESC NULLS LAST`.
    A B-tree can only supply an ordering it actually holds, so the index sat
    unused and page 1 of the party list was a parallel sequential scan and a
    full sort. Rebuilding it with the null placement written out, and with the
    soft-delete condition the queries all carry, makes it reachable.

    `ix_party_tenant_recent` goes because PTY-02 BR-4 deleted the query it
    existed for: the list no longer issues a request without a status.

    Both rebuilds take an ACCESS EXCLUSIVE lock for the duration. On a table of
    this size that is milliseconds, and the product has no live tenants; when it
    does, this pair wants `CREATE INDEX CONCURRENTLY` in a non-atomic migration
    instead.
    """


    dependencies = [
        ("parties", "0003_opening_balance"),
        ("platform", "0007_temp_credentials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="party",
            name="ix_party_tenant_activity",
        ),
        migrations.RemoveIndex(
            model_name="party",
            name="ix_party_tenant_recent",
        ),
        migrations.AddIndex(
            model_name="party",
            index=models.Index(
                models.F("tenant"),
                models.F("status"),
                models.OrderBy(models.F("last_activity_at"), descending=True, nulls_last=True),
                condition=models.Q(("deleted_at__isnull", True)),
                name="ix_party_tenant_activity",
            ),
        ),
    ]
