# Generated by Django 5.2.6 on 2026-09-22 16:00

import apps.common.db.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """PTY-05 — tags.

    Two small tables and two indexes, and the interesting one is the
    case-insensitive unique constraint on `lower(name)`. The service normalises
    before it looks a tag up, and a service is not a constraint: two staff
    members creating "Camp Area" and "camp area" from two party forms in the
    same second both pass their own check and both insert. Only the database
    can refuse the second, and `get_or_create` then catches the IntegrityError
    and re-reads, so both parties end up on one tag (EC-3).

    `IX(tag_id)` on the join exists because `U(party_id, tag_id)` leads with
    `party_id`: it serves party -> tags and cannot serve tag -> parties, which
    is the direction both the manager's `party_count` and the list's tag filter
    read in.
    """


    dependencies = [
        ("parties", "0004_list_index_null_placement"),
        ("platform", "0007_temp_credentials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "parties_tag",
            },
        ),
        migrations.CreateModel(
            name="PartyTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_tags",
                        to="parties.party",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_tags",
                        to="parties.tag",
                    ),
                ),
            ],
            options={
                "db_table": "parties_party_tag",
            },
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("tenant"),
                name="uq_tag_tenant_lower_name",
            ),
        ),
        migrations.AddIndex(
            model_name="partytag",
            index=models.Index(fields=["tag"], name="ix_party_tag_tag"),
        ),
        migrations.AddConstraint(
            model_name="partytag",
            constraint=models.UniqueConstraint(fields=("party", "tag"), name="uq_party_tag"),
        ),
    ]
