# Generated by Django 5.2.6 on 2026-09-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0005_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="parties", through="parties.PartyTag", to="parties.tag"
            ),
        ),
    ]
