# Generated by Django 5.2.6 on 2026-09-24 06:39

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


#: Frozen copies of `constants.CATEGORY_COLORS` / `SEEDED_CATEGORY_CODES`: a
#: migration must not import app code that can change after it has run.
_PALETTE = ("viz-1", "viz-2", "viz-3", "viz-4", "viz-5", "viz-6", "viz-7", "viz-8")
_SEEDED = (
    "rent",
    "salaries",
    "electricity",
    "transport",
    "purchases_misc",
    "food",
    "marketing",
    "fees",
    "other",
)


def backfill_category_colours(apps, schema_editor):
    """EXP-02 FR-1 — every existing category gets a palette token.

    Seeded rows take the token of their code's position in the seed, so every
    tenant's "Rent" is the same colour; a tenant's own rows (onboarding's
    business-type extras) go round the palette in creation order. Rows that
    already carry a colour are left alone, so re-running is a no-op.
    """
    Category = apps.get_model("expenses", "ExpenseCategory")
    by_tenant: dict = {}
    for row in Category.objects.filter(color="").order_by("tenant_id", "sort_order", "created_at"):
        code = row.system_code or ""
        if code in _SEEDED:
            row.color = _PALETTE[_SEEDED.index(code) % len(_PALETTE)]
        else:
            index = by_tenant.get(row.tenant_id, len(_SEEDED))
            row.color = _PALETTE[index % len(_PALETTE)]
            by_tenant[row.tenant_id] = index + 1
        row.save(update_fields=["color"])


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        ("parties", "0008_add_ordering_and_search_indexes_to_party"),
        ("platform", "0009_normalise_user_mobiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expensecategory",
            name="color",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=32)),
                ("expense_date", models.DateField()),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("bank", "Bank"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "upi_app",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("phonepe", "PhonePe"),
                            ("gpay", "Google Pay"),
                            ("paytm", "Paytm"),
                            ("bhim", "BHIM"),
                            ("amazonpay", "Amazon Pay"),
                            ("cred", "CRED"),
                            ("whatsapp", "WhatsApp Pay"),
                            ("navi", "Navi"),
                            ("supermoney", "super.money"),
                            ("bank_app", "Bank's own app"),
                            ("other", "Other UPI app"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("paid", models.BooleanField(default=True)),
                ("due_on", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("recorded", "Recorded"), ("void", "Void")],
                        default="recorded",
                        max_length=10,
                    ),
                ),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=160, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="expenses",
                        to="expenses.expensecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="expenses",
                        to="parties.party",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "expense",
                "verbose_name_plural": "expenses",
                "db_table": "expenses_expense",
                "indexes": [
                    models.Index(
                        fields=["tenant", "-expense_date", "-created_at"],
                        name="ix_expense_tenant_date",
                    ),
                    models.Index(
                        fields=["tenant", "status", "-expense_date"],
                        name="ix_expense_tenant_status",
                    ),
                    models.Index(fields=["tenant", "category"], name="ix_expense_tenant_category"),
                    models.Index(
                        condition=models.Q(("party__isnull", False)),
                        fields=["tenant", "party", "-expense_date"],
                        name="ix_expense_tenant_party",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "number"), name="uq_expense_number"),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="ck_expense_amount_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("paid", True), ("party__isnull", False), _connector="OR"
                        ),
                        name="ck_expense_unpaid_has_party",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("mode__isnull", False), ("paid", True)),
                            models.Q(("mode__isnull", True), ("paid", False)),
                            _connector="OR",
                        ),
                        name="ck_expense_mode_iff_paid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("upi_app__isnull", True), ("mode", "upi"), _connector="OR"
                        ),
                        name="ck_expense_upi_app_needs_upi",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "recorded"),
                            models.Q(("status", "void"), ("void_reason__isnull", False)),
                            _connector="OR",
                        ),
                        name="ck_expense_void_has_reason",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_category_colours, migrations.RunPython.noop),
    ]
