// GENERATED by scripts/split-locales.mjs from locales/catalogues.json — do not
// edit by hand; change the table and re-run the script.
import type { Locale } from 'src/types/domain.types';

import adminEn from 'locales/catalogues/admin.en.json';
import adminHi from 'locales/catalogues/admin.hi.json';
import auditEn from 'locales/catalogues/audit.en.json';
import auditHi from 'locales/catalogues/audit.hi.json';
import authEn from 'locales/catalogues/auth.en.json';
import authHi from 'locales/catalogues/auth.hi.json';
import brandingEn from 'locales/catalogues/branding.en.json';
import brandingHi from 'locales/catalogues/branding.hi.json';
import businessProfileEn from 'locales/catalogues/businessProfile.en.json';
import businessProfileHi from 'locales/catalogues/businessProfile.hi.json';
import cashbookEn from 'locales/catalogues/cashbook.en.json';
import cashbookHi from 'locales/catalogues/cashbook.hi.json';
import dataEn from 'locales/catalogues/data.en.json';
import dataHi from 'locales/catalogues/data.hi.json';
import dataStatusEn from 'locales/catalogues/dataStatus.en.json';
import dataStatusHi from 'locales/catalogues/dataStatus.hi.json';
import expensesEn from 'locales/catalogues/expenses.en.json';
import expensesHi from 'locales/catalogues/expenses.hi.json';
import exportsEn from 'locales/catalogues/exports.en.json';
import exportsHi from 'locales/catalogues/exports.hi.json';
import importsEn from 'locales/catalogues/imports.en.json';
import importsHi from 'locales/catalogues/imports.hi.json';
import inventoryEn from 'locales/catalogues/inventory.en.json';
import inventoryHi from 'locales/catalogues/inventory.hi.json';
import itemPickerEn from 'locales/catalogues/itemPicker.en.json';
import itemPickerHi from 'locales/catalogues/itemPicker.hi.json';
import itemsEn from 'locales/catalogues/items.en.json';
import itemsHi from 'locales/catalogues/items.hi.json';
import ledgerEn from 'locales/catalogues/ledger.en.json';
import ledgerHi from 'locales/catalogues/ledger.hi.json';
import legalEn from 'locales/catalogues/legal.en.json';
import legalHi from 'locales/catalogues/legal.hi.json';
import moneyEn from 'locales/catalogues/money.en.json';
import moneyHi from 'locales/catalogues/money.hi.json';
import movementEn from 'locales/catalogues/movement.en.json';
import movementHi from 'locales/catalogues/movement.hi.json';
import notificationsEn from 'locales/catalogues/notifications.en.json';
import notificationsHi from 'locales/catalogues/notifications.hi.json';
import onboardingEn from 'locales/catalogues/onboarding.en.json';
import onboardingHi from 'locales/catalogues/onboarding.hi.json';
import partiesEn from 'locales/catalogues/parties.en.json';
import partiesHi from 'locales/catalogues/parties.hi.json';
import partyPickerEn from 'locales/catalogues/partyPicker.en.json';
import partyPickerHi from 'locales/catalogues/partyPicker.hi.json';
import paymentActionsEn from 'locales/catalogues/paymentActions.en.json';
import paymentActionsHi from 'locales/catalogues/paymentActions.hi.json';
import paymentsEn from 'locales/catalogues/payments.en.json';
import paymentsHi from 'locales/catalogues/payments.hi.json';
import periodEn from 'locales/catalogues/period.en.json';
import periodHi from 'locales/catalogues/period.hi.json';
import planEn from 'locales/catalogues/plan.en.json';
import planHi from 'locales/catalogues/plan.hi.json';
import purchasesEn from 'locales/catalogues/purchases.en.json';
import purchasesHi from 'locales/catalogues/purchases.hi.json';
import remindersEn from 'locales/catalogues/reminders.en.json';
import remindersHi from 'locales/catalogues/reminders.hi.json';
import reportsEn from 'locales/catalogues/reports.en.json';
import reportsHi from 'locales/catalogues/reports.hi.json';
import salesEn from 'locales/catalogues/sales.en.json';
import salesHi from 'locales/catalogues/sales.hi.json';
import sessionsEn from 'locales/catalogues/sessions.en.json';
import sessionsHi from 'locales/catalogues/sessions.hi.json';
import settingsEn from 'locales/catalogues/settings.en.json';
import settingsHi from 'locales/catalogues/settings.hi.json';
import settingsGateEn from 'locales/catalogues/settingsGate.en.json';
import settingsGateHi from 'locales/catalogues/settingsGate.hi.json';
import shareEn from 'locales/catalogues/share.en.json';
import shareHi from 'locales/catalogues/share.hi.json';
import stockEn from 'locales/catalogues/stock.en.json';
import stockHi from 'locales/catalogues/stock.hi.json';
import taxReportsEn from 'locales/catalogues/taxReports.en.json';
import taxReportsHi from 'locales/catalogues/taxReports.hi.json';
import teamEn from 'locales/catalogues/team.en.json';
import teamHi from 'locales/catalogues/team.hi.json';
import tenantEn from 'locales/catalogues/tenant.en.json';
import tenantHi from 'locales/catalogues/tenant.hi.json';
import validationEn from 'locales/catalogues/validation.en.json';
import validationHi from 'locales/catalogues/validation.hi.json';
import shellEn from 'locales/en.json';
import shellHi from 'locales/hi.json';

/**
 * Every catalogue at once, per language — what `renderWithProviders` hands
 * `IntlProvider`, and what a test reads when it looks a string up.
 *
 * TESTS ONLY. The product never loads this: each screen imports the
 * catalogues it renders (`src/i18n/catalogues/*`), and
 * `scripts/check-locales.mjs` proves over the import graph that it does.
 * Handing the tests the union is what keeps a missing KEY loud here — a key
 * that exists in no catalogue still renders raw and fails the assertion —
 * without every test having to know which screen loads what.
 */
export const en: Readonly<Record<string, string>> = {
  ...shellEn,
  ...adminEn,
  ...auditEn,
  ...authEn,
  ...brandingEn,
  ...businessProfileEn,
  ...cashbookEn,
  ...dataEn,
  ...dataStatusEn,
  ...expensesEn,
  ...exportsEn,
  ...importsEn,
  ...inventoryEn,
  ...itemPickerEn,
  ...itemsEn,
  ...ledgerEn,
  ...legalEn,
  ...moneyEn,
  ...movementEn,
  ...notificationsEn,
  ...onboardingEn,
  ...partiesEn,
  ...partyPickerEn,
  ...paymentActionsEn,
  ...paymentsEn,
  ...periodEn,
  ...planEn,
  ...purchasesEn,
  ...remindersEn,
  ...reportsEn,
  ...salesEn,
  ...sessionsEn,
  ...settingsEn,
  ...settingsGateEn,
  ...shareEn,
  ...stockEn,
  ...taxReportsEn,
  ...teamEn,
  ...tenantEn,
  ...validationEn,
};

export const hi: Readonly<Record<string, string>> = {
  ...shellHi,
  ...adminHi,
  ...auditHi,
  ...authHi,
  ...brandingHi,
  ...businessProfileHi,
  ...cashbookHi,
  ...dataHi,
  ...dataStatusHi,
  ...expensesHi,
  ...exportsHi,
  ...importsHi,
  ...inventoryHi,
  ...itemPickerHi,
  ...itemsHi,
  ...ledgerHi,
  ...legalHi,
  ...moneyHi,
  ...movementHi,
  ...notificationsHi,
  ...onboardingHi,
  ...partiesHi,
  ...partyPickerHi,
  ...paymentActionsHi,
  ...paymentsHi,
  ...periodHi,
  ...planHi,
  ...purchasesHi,
  ...remindersHi,
  ...reportsHi,
  ...salesHi,
  ...sessionsHi,
  ...settingsHi,
  ...settingsGateHi,
  ...shareHi,
  ...stockHi,
  ...taxReportsHi,
  ...teamHi,
  ...tenantHi,
  ...validationHi,
};

export const ALL_MESSAGES: Readonly<Record<Locale, Readonly<Record<string, string>>>> = { en, hi };
