import { screen } from '@testing-library/react';

import { useTranslation } from 'src/hooks/useTranslation';
import { renderWithProviders } from 'src/tests/renderWithProviders';

import { StatementPrintView } from 'modules/DigiKhaato/features/ledger/components/print/StatementPrintView';
import { PaymentReceiptPrint } from 'modules/DigiKhaato/features/payments/components/print/PaymentReceiptPrint';
import type { Payment } from 'modules/DigiKhaato/features/payments/types/payment.types';
import { InvoicePrintA4 } from 'modules/DigiKhaato/features/sales/components/print/InvoicePrintA4';
import { InvoicePrintThermal80 } from 'modules/DigiKhaato/features/sales/components/print/InvoicePrintThermal80';
import { PublicDocumentPageContent } from 'modules/DigiKhaato/features/sales/components/public/PublicDocumentPageContent';
import type { PrintBranding } from 'modules/DigiKhaato/features/sales/redux/salesThunk';
import {
  billOfSupply,
  makeDocument,
  publicWire,
} from 'modules/DigiKhaato/features/sales/testing/salesFixtures';
import type { SalesDocument } from 'modules/DigiKhaato/features/sales/types/sales.types';

jest.mock('src/api/AxiosInstances', () => ({
  ...jest.requireActual('src/api/AxiosInstances'),
  publicApi: { get: jest.fn() },
}));

/**
 * CR-2026-09-29-BRAND-A — the owner, verbatim in essence: "In any PDF I don't
 * want any domain — instead keep the tenant name; don't keep the domain name in
 * any place."
 *
 * Everything below is something a merchant's CUSTOMER receives: the A4 and
 * 80 mm bills (tax invoice, bill of supply, estimate, credit note), the A5
 * payment receipt, the party statement, and the share page `/d/<token>` the
 * customer opens from WhatsApp. Each used to sign itself "Generated by
 * DigiKhaato" or "Powered by DigiKhaato". Each must now name the shop that
 * issued it and nothing of ours — not the old name, not the new one, not the
 * domain — even when the tenant's branding row itself carries the product's
 * name (the fixture's `appName` is deliberately "YourKhata", which is exactly
 * what a default-branded tenant's row holds).
 *
 * The check reads the whole rendered HTML, not just the text, so a product
 * URL in an `href`, a `src` or an `alt` fails it too.
 */

const FORBIDDEN = ['digikhaato', 'digi khaato', 'yourkhata', 'yourkhata.com', 'udhaarbook'];

const expectShopOnly = (container: HTMLElement, shop: string): void => {
  const html = container.innerHTML.toLowerCase();
  for (const word of FORBIDDEN) expect(html).not.toContain(word);
  expect(container.textContent ?? '').toContain(shop);
};

/** A tenant on default branding: its row still says the product's name. */
const BRANDING: PrintBranding = {
  logoUrl: null,
  signatureUrl: null,
  docHeader: '',
  docFooter: 'Goods once sold will not be taken back.',
  appName: 'YourKhata',
  primaryHex: '#4A47D6',
};

const SHOP = 'Sharma General Store';

function A4({ doc }: Readonly<{ doc: SalesDocument }>) {
  const { t } = useTranslation();
  return <InvoicePrintA4 doc={doc} upi={null} branding={BRANDING} locale="en" t={t} />;
}

function Thermal({ doc }: Readonly<{ doc: SalesDocument }>) {
  const { t } = useTranslation();
  return <InvoicePrintThermal80 doc={doc} upi={null} branding={BRANDING} t={t} />;
}

const documents: ReadonlyArray<[string, () => SalesDocument]> = [
  ['a tax invoice', () => makeDocument()],
  ['a bill of supply', () => billOfSupply()],
  ['an estimate', () => makeDocument({ kind: 'estimate', number: 'EST/26-27/0003' })],
  [
    'a credit note',
    () =>
      makeDocument({
        kind: 'credit_note',
        number: 'CN/26-27/0001',
        links: { against: { id: 'd1', number: 'INV/26-27/0001', document_date: '2026-09-24' } },
      }),
  ],
];

describe.each(documents)('%s', (_label, build) => {
  it('prints the shop, and no product name or domain, on A4', () => {
    const { container } = renderWithProviders(<A4 doc={build()} />);
    expectShopOnly(container, SHOP);
    expect(screen.getByTestId('print-issued-by')).toHaveTextContent(`Issued by ${SHOP}`);
  });

  it('prints the shop, and no product name or domain, on the 80 mm roll', () => {
    const { container } = renderWithProviders(<Thermal doc={build()} />);
    expectShopOnly(container, SHOP);
    expect(screen.getByTestId('print-issued-by')).toHaveTextContent(`Issued by ${SHOP}`);
  });
});

it('signs the A5 payment receipt with the shop, never the product', () => {
  const payment: Payment = {
    id: 'pay1',
    number: 'RCT/26-27/0017',
    direction: 'in',
    party: { id: 'p1', name: 'Ramesh Traders', mobile: null },
    paymentDate: '2026-09-28',
    amount: '1200.00',
    modeBreakup: [{ mode: 'cash', amount: '1200.00', reference: '', upiApp: null }],
    primaryMode: 'cash',
    reference: '',
    note: '',
    status: 'recorded',
    unallocatedAmount: '1200.00',
    allocations: [],
    partyBalanceAfter: '0.00',
    context: null,
    business: {
      name: 'Sharma Kirana Store',
      legalName: null,
      gstin: null,
      phone: null,
      address: {},
      upiVpa: null,
    },
    voidReason: null,
    voidedAt: null,
    voidedBy: null,
    createdBy: null,
    createdAt: '2026-09-28T10:00:00Z',
  };
  function Receipt() {
    const { t } = useTranslation();
    return (
      <PaymentReceiptPrint
        payment={payment}
        branding={BRANDING}
        staticQr={null}
        locale="en"
        t={t}
      />
    );
  }
  const { container } = renderWithProviders(<Receipt />);
  expectShopOnly(container, 'Sharma Kirana Store');
  expect(screen.getByTestId('receipt-issued-by')).toHaveTextContent(
    'Issued by Sharma Kirana Store'
  );
});

it('signs the party statement with the shop, never the product', () => {
  const { container } = renderWithProviders(
    <StatementPrintView
      party={{ id: 'p1', name: 'Ramesh Traders', mobileMasked: null }}
      period={{ from: '2026-04-01', to: '2026-09-23' }}
      summary={{
        openingBalance: '0.00',
        closingBalance: '1800.00',
        totalDebit: '2800.00',
        totalCredit: '1000.00',
        hasEntriesBeforeOpening: false,
      }}
      rows={[]}
      shopName="Kumar Kirana Store"
      shop={null}
      generatedAt="2026-09-24T10:00:00+05:30"
    />
  );
  expectShopOnly(container, 'Kumar Kirana Store');
  expect(screen.getByTestId('statement-issued-by')).toHaveTextContent(
    'Issued by Kumar Kirana Store'
  );
});

describe('the customer share page /d/<token>', () => {
  const get = (jest.requireMock('src/api/AxiosInstances') as { publicApi: { get: jest.Mock } })
    .publicApi.get;

  beforeEach(() => {
    get.mockReset();
    document.title = '';
  });

  it('says who shared it, and carries no product name, logo or domain', async () => {
    get.mockResolvedValueOnce({ data: { data: publicWire() } });
    const { container } = renderWithProviders(<PublicDocumentPageContent token="tokBrand_AbCd" />);

    expect(await screen.findByTestId('public-shared-by')).toHaveTextContent(`Shared by ${SHOP}`);
    expect(screen.queryByTestId('public-powered-by')).not.toBeInTheDocument();
    expectShopOnly(container, SHOP);
    // The tab, which is also the "Save as PDF" filename, is the bill's number.
    expect(document.title).toBe('INV/26-27/0001');
  });

  it('names nobody at all on the unavailable screen', async () => {
    get.mockRejectedValueOnce({
      code: 'not_found',
      message: 'x',
      details: {},
      requestId: null,
      status: 404,
      warnings: [],
    });
    const { container } = renderWithProviders(<PublicDocumentPageContent token="tokGone_AbCd" />);

    expect(await screen.findByTestId('public-unavailable')).toBeInTheDocument();
    const html = container.innerHTML.toLowerCase();
    for (const word of FORBIDDEN) expect(html).not.toContain(word);
  });
});
