# Generated by Django 5.2.6 on 2026-09-19 02:41

import apps.common.db.fields
import apps.platform_app.models.user
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mobile", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("full_name", models.CharField(max_length=120)),
                ("locale", models.CharField(default="en", max_length=8)),
                ("is_super_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("mfa_secret", models.CharField(blank=True, max_length=64, null=True)),
                ("token_epoch", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "platform_user",
                "indexes": [models.Index(fields=["is_super_admin"], name="ix_user_superadmin")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("email__isnull", False)),
                        fields=("email",),
                        name="uq_user_email_notnull",
                    )
                ],
            },
            managers=[
                ("objects", apps.platform_app.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OtpChallenge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mobile", models.CharField(max_length=15)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("signup", "Signup"),
                            ("verify", "Verify"),
                            ("reset", "Reset"),
                        ],
                        max_length=16,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("attempts", models.SmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("device_hint", models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                "verbose_name": "OTP challenge",
                "verbose_name_plural": "OTP challenges",
                "db_table": "platform_otp_challenge",
                "indexes": [
                    models.Index(fields=["mobile", "created_at"], name="ix_otp_mobile_created"),
                    models.Index(fields=["expires_at"], name="ix_otp_expires"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("attempts__gte", 0)), name="ck_otp_attempts"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "modules",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32), default=list, size=None
                    ),
                ),
                ("limits", models.JSONField(blank=True, default=dict)),
                (
                    "price_inr_month",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "plan",
                "verbose_name_plural": "plans",
                "db_table": "platform_plan",
                "indexes": [models.Index(fields=["is_active"], name="ix_plan_active")],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("branding", models.JSONField(blank=True, default=dict)),
                (
                    "allowed_modules",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32), default=list, size=None
                    ),
                ),
                ("support_contact", models.JSONField(blank=True, default=dict)),
                (
                    "hostnames",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=253),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "default_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="platform.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "partner",
                "verbose_name_plural": "partners",
                "db_table": "platform_partner",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("legal_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("retail", "Retail"),
                            ("wholesale", "Wholesale"),
                            ("distribution", "Distribution"),
                            ("services", "Services"),
                            ("trader", "Trader"),
                            ("manufacturer", "Manufacturer"),
                            ("professional", "Professional"),
                            ("food", "Food"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "gst_type",
                    models.CharField(
                        choices=[
                            ("unregistered", "Unregistered"),
                            ("composition", "Composition"),
                            ("regular", "Regular"),
                        ],
                        default="unregistered",
                        max_length=16,
                    ),
                ),
                (
                    "gstin",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 15-character GSTIN.",
                                regex="^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$",
                            )
                        ],
                    ),
                ),
                (
                    "pan",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-character PAN.",
                                regex="^[A-Z]{5}[0-9]{4}[A-Z]{1}$",
                            )
                        ],
                    ),
                ),
                ("state_code", models.CharField(max_length=2)),
                ("address", models.JSONField(blank=True, default=dict)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("locale", models.CharField(default="en", max_length=8)),
                ("fy_start_month", models.SmallIntegerField(default=4)),
                (
                    "enabled_modules",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32), default=list, size=None
                    ),
                ),
                ("branding", models.JSONField(blank=True, default=dict)),
                ("bank_details", models.JSONField(blank=True, default=dict)),
                ("upi_vpa", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("pending_deletion", "Pending deletion"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("deletion_requested_at", models.DateTimeField(blank=True, null=True)),
                ("onboarding_step", models.SmallIntegerField(default=0)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tenants",
                        to="platform.partner",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tenants",
                        to="platform.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "tenant",
                "verbose_name_plural": "tenants",
                "db_table": "platform_tenant",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("family_id", models.UUIDField()),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("device_label", models.CharField(blank=True, max_length=120, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="platform.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "db_table": "platform_session",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=120)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="roles",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "db_table": "platform_role",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("permissions_override", models.JSONField(blank=True, default=dict)),
                ("permissions_version", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="memberships",
                        to="platform.role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="memberships",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "membership",
                "verbose_name_plural": "memberships",
                "db_table": "platform_membership",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("dead_letter", "Dead letter"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=100)),
                ("run_after", models.DateTimeField()),
                ("attempts", models.SmallIntegerField(default=0)),
                ("max_attempts", models.SmallIntegerField(default=5)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=64, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("idempotency_token", models.CharField(blank=True, max_length=128, null=True)),
                ("scheduled_key", models.CharField(blank=True, max_length=96, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="jobs",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "job",
                "verbose_name_plural": "jobs",
                "db_table": "platform_job",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mobile", models.CharField(max_length=15)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "accepted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="invitations",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
                "db_table": "platform_invitation",
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("scope", models.CharField(max_length=48)),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In progress"), ("completed", "Completed")],
                        max_length=12,
                    ),
                ),
                ("response_status", models.SmallIntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="idempotency_keys",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "idempotency key",
                "verbose_name_plural": "idempotency keys",
                "db_table": "platform_idempotency_key",
            },
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=24)),
                ("fy_label", models.CharField(max_length=9)),
                ("prefix", models.CharField(blank=True, default="", max_length=12)),
                ("next_number", models.IntegerField(default=1)),
                ("padding", models.SmallIntegerField(default=4)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sequences",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "document sequence",
                "verbose_name_plural": "document sequences",
                "db_table": "platform_document_sequence",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("system", "System"),
                            ("webhook", "Webhook"),
                            ("super_admin", "Super admin"),
                        ],
                        default="user",
                        max_length=16,
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("entity_type", models.CharField(max_length=48)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "db_table": "platform_audit_log",
            },
        ),
        migrations.CreateModel(
            name="TenantSetting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("schema_version", models.SmallIntegerField(default=1)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="settings",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "tenant setting",
                "verbose_name_plural": "tenant settings",
                "db_table": "platform_tenant_setting",
            },
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["status"], name="ix_partner_status"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["partner"], name="ix_tenant_partner"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["status"], name="ix_tenant_status"),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("gstin__isnull", False), models.Q(("status", "deleted"), _negated=True)
                ),
                fields=("partner", "gstin"),
                name="uq_tenant_partner_gstin",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(("fy_start_month__gte", 1), ("fy_start_month__lte", 12)),
                name="ck_tenant_fy_start_month",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["user", "revoked_at"], name="ix_session_user_revoked"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["family_id"], name="ix_session_family"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="uq_role_tenant_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", True)),
                fields=("code",),
                name="uq_role_system_code",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["tenant", "status"], name="ix_membership_tenant_status"),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "tenant"), name="uq_membership_user_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(("status", "queued")),
                fields=["priority", "run_after", "created_at"],
                name="ix_job_claim",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(("status", "running")), fields=["locked_at"], name="ix_job_stuck"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["tenant", "-created_at"], name="ix_job_tenant_recent"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status", "-created_at"], name="ix_job_status_recent"),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attempts__gte", 0),
                    (
                        "attempts__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("max_attempts"), "+", models.Value(1)
                        ),
                    ),
                ),
                name="ck_job_attempts",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("idempotency_token__isnull", False),
                    ("status__in", ["queued", "running", "succeeded"]),
                ),
                fields=("tenant", "job_type", "idempotency_token"),
                name="uq_job_idem",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scheduled_key__isnull", False)),
                fields=("scheduled_key",),
                name="uq_job_scheduled",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["tenant", "status"], name="ix_invitation_tenant_status"),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["expires_at"], name="ix_idempotency_expires"),
        ),
        migrations.AddConstraint(
            model_name="idempotencykey",
            constraint=models.UniqueConstraint(
                fields=("tenant", "scope", "key"), name="uq_idempotency_tenant_scope_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "kind", "fy_label"), name="uq_document_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.CheckConstraint(
                condition=models.Q(("next_number__gte", 1)), name="ck_sequence_next_number"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["tenant", "-created_at"], name="ix_audit_tenant_recent"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "entity_type", "entity_id"], name="ix_audit_tenant_entity"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantsetting",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="uq_tenant_setting_key"
            ),
        ),
    ]
