# Generated by Django 5.2.6 on 2026-09-19 06:08

import apps.common.db.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0002_add_job_payload_size_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope", models.CharField(max_length=32)),
                ("key", models.CharField(max_length=64)),
                ("window_start", models.DateTimeField()),
                ("count", models.IntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_hit_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "rate limit counter",
                "verbose_name_plural": "rate limit counters",
                "db_table": "platform_rate_limit",
            },
        ),
        migrations.AlterField(
            model_name="idempotencykey",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="idempotency_keys",
                to="platform.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotencykey",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tenant__isnull", True)),
                fields=("user", "scope", "key"),
                name="uq_idempotency_user_scope_key",
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimit",
            index=models.Index(fields=["window_start"], name="ix_rate_limit_window"),
        ),
        migrations.AddConstraint(
            model_name="ratelimit",
            constraint=models.UniqueConstraint(
                fields=("scope", "key"), name="uq_rate_limit_scope_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="ratelimit",
            constraint=models.CheckConstraint(
                condition=models.Q(("count__gte", 0)), name="ck_rate_limit_count"
            ),
        ),
    ]
