"""`platform_auth_token` — the single-use link token (Part 27 §27.4.2, DEC-010).

One table for the password-reset link and the address-verification link: they
are the same object with a different `purpose` — a random secret delivered out
of band, spendable once, dead after its window. Part 21 §21.3.1 does not define
this table; `CR-LOG` carries the request that it does.
"""

# Generated by Django 5.2.6 on 2026-09-19 07:26

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0004_email_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("password_reset", "Password reset"),
                            ("email_verify", "Email verification"),
                        ],
                        max_length=24,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "auth token",
                "verbose_name_plural": "auth tokens",
                "db_table": "platform_auth_token",
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "created_at"], name="ix_auth_token_user"
                    ),
                    models.Index(fields=["expires_at"], name="ix_auth_token_expires"),
                ],
            },
        ),
    ]
