# Generated by Django 5.2.6 on 2026-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0006_invitation_email_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="password_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
