# Generated by Django 5.2.6 on 2026-09-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0007_temp_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_password_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="platform.tenant",
            ),
        ),
    ]
