# Generated by Django 5.2.6 on 2026-09-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0009_normalise_user_mobiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "actor", "-created_at"], name="ix_audit_tenant_actor"
            ),
        ),
    ]
