# Generated by Django 5.2.6 on 2026-09-24 15:14

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0010_session_last_used_audit_actor_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportAccess",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("granted", "Granted"),
                            ("denied", "Denied"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="requested",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="support_accesses",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "support access",
                "verbose_name_plural": "support accesses",
                "db_table": "platform_support_access",
            },
        ),
        migrations.CreateModel(
            name="ImpersonationSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.UUIDField(blank=True, null=True)),
                ("jti_hash", models.CharField(max_length=64, unique=True)),
                ("reason", models.CharField(max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("end_reason", models.CharField(blank=True, max_length=24, null=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sessions",
                        to="platform.supportaccess",
                    ),
                ),
            ],
            options={
                "verbose_name": "impersonation session",
                "verbose_name_plural": "impersonation sessions",
                "db_table": "platform_impersonation_session",
            },
        ),
        migrations.AddIndex(
            model_name="supportaccess",
            index=models.Index(fields=["tenant", "-created_at"], name="ix_support_access_tenant"),
        ),
        migrations.AddIndex(
            model_name="impersonationsession",
            index=models.Index(fields=["tenant", "-created_at"], name="ix_impersonation_tenant"),
        ),
    ]
