# Generated by Django 5.2.6 on 2026-09-29 21:18

"""A8 (ADR-051, FRD 00 PLT-X07 §5): `fy_label` admits the perpetual sentinel `'*'`.

A perpetual number kind (a library's accession register, a member code) keeps
one `platform_document_sequence` row with `fy_label = '*'`. The CHECK makes that
sentinel safe in a column named for financial years: `'*'` or `YYYY-YY`, nothing
else. PostgreSQL validates it against every existing row as it is added, and
every row written so far is `YYYY-YY` (`fy_label_for`); the reverse drops it.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0011_support_access_impersonation"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fy_label", "*"), ("fy_label__regex", "^[0-9]{4}-[0-9]{2}$"), _connector="OR"
                ),
                name="ck_sequence_fy_label",
            ),
        ),
    ]
