"""A9b (ADR-055, FRD 00 PLT-X08 §5): `platform_closed_day`, the calendar's dated closures.

Tenant-scoped (`TenantModel`); one row per `(tenant, date, module)` with NULLS NOT
DISTINCT so a tenant-wide closure cannot be entered twice; reversible (drops the
table). Weekly closed weekdays are settings rows, not rows here.
"""

# Generated by Django 5.2.6 on 2026-09-29 21:35

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0012_sequence_perpetual"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedDay",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.CharField(max_length=60)),
                ("module", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "closed day",
                "verbose_name_plural": "closed days",
                "db_table": "platform_closed_day",
                "ordering": ("date", "module"),
                "indexes": [models.Index(fields=["tenant", "date"], name="ix_closed_day_range")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "date", "module"),
                        name="uq_closed_day",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
