import { chromium } from 'playwright';
const FE='http://localhost:3000', BE='http://localhost:8000/api/v1';
const stamp=Date.now();
const api=async(m,p,b,t,extra={})=>{const r=await fetch(BE+p,{method:m,headers:{'Content-Type':'application/json','X-Client':'api',...(t?{Authorization:`Bearer ${t}`}:{}),...extra},body:b?JSON.stringify(b):undefined});return {status:r.status, body:await r.json().catch(()=>null)};};
const email=`probe-${stamp}@shop.test`, password='Dukaan2026x';
let r=await api('POST','/auth/register',{email,password,full_name:'Probe'});
const t0=r.body.data.access_token;
await api('POST','/tenants',{name:'Probe Shop',business_type:'retail',state_code:'27'},t0,{'Idempotency-Key':`t-${stamp}`});
r=await api('POST','/auth/login',{email,password});
const token=r.body.data.access_token;
r=await api('POST','/parties',{name:'Probe Party',is_customer:true},token,{'Idempotency-Key':`p-${stamp}`});
const partyId=r.body.data.id;

const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1440,height:900}});
const p=await ctx.newPage();
await p.goto(`${FE}/login`,{waitUntil:'domcontentloaded'});
await p.fill('input[type="email"]',email); await p.fill('input[type="password"]',password);
await p.click('button[type="submit"]'); await p.waitForTimeout(2500);
await p.goto(`${FE}/parties/${partyId}`,{waitUntil:'domcontentloaded'});
await p.waitForSelector('text=Transactions'); await p.waitForTimeout(1200);
await p.getByRole('button',{name:/You gave/}).first().click();
await p.waitForSelector('role=dialog'); await p.waitForTimeout(900);
const amount = p.getByLabel('Amount');
console.log('aria-invalid:', await amount.getAttribute('aria-invalid'));
console.log('focused:', await p.evaluate(()=>document.activeElement?.getAttribute('id') || document.activeElement?.tagName));
const body = await p.locator('role=dialog').innerText();
console.log('--- drawer text ---\n'+body);
await b.close();
