# Generated by Django 5.2.6 on 2026-09-23 00:09

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parties", "0007_tag_palette_tokens"),
        ("platform", "0007_temp_credentials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")], max_length=6
                    ),
                ),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
                ("entry_date", models.DateField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening balance"),
                            ("manual_gave", "You gave"),
                            ("manual_got", "You got"),
                            ("invoice", "Invoice"),
                            ("credit_note", "Credit note"),
                            ("purchase_bill", "Purchase bill"),
                            ("debit_note", "Debit note"),
                            ("payment_in", "Payment received"),
                            ("payment_out", "Payment made"),
                            ("expense", "Expense"),
                            ("write_off", "Write-off"),
                            ("interest", "Interest"),
                            ("reversal", "Reversal"),
                            ("correction", "Correction"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("sales_document", "Sales document"),
                            ("purchase_document", "Purchase document"),
                            ("payment", "Payment"),
                            ("expense", "Expense"),
                            ("ledger_entry", "Ledger entry"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "payment_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("bank", "Bank"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("posted", "Posted"), ("reversed", "Reversed")],
                        default="posted",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=160, null=True)),
                (
                    "running_balance_after",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ledger_entries",
                        to="parties.party",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="ledger.ledgerentry",
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="ledger.ledgerentry",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="ledger.ledgerentry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "ledger entry",
                "verbose_name_plural": "ledger entries",
                "db_table": "ledger_entry",
                "indexes": [
                    models.Index(
                        fields=["tenant", "party", "-entry_date", "-created_at"],
                        name="ix_ledger_party_date",
                    ),
                    models.Index(
                        fields=["tenant", "source_type", "source_id"], name="ix_ledger_source"
                    ),
                    models.Index(fields=["tenant", "entry_date"], name="ix_ledger_tenant_date"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="ck_ledger_entry_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("entry_type", "reversal"), ("reverses__isnull", False)),
                            models.Q(("entry_type", "reversal"), _negated=True),
                            _connector="OR",
                        ),
                        name="ck_ledger_entry_reversal_has_source",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("direction", "credit"),
                            models.Q(("direction", "debit"), ("payment_mode__isnull", True)),
                            _connector="OR",
                        ),
                        name="ck_ledger_entry_debit_has_no_mode",
                    ),
                ],
            },
        ),
    ]
