# Generated by Django 5.2.6 on 2026-09-24 06:40

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_entry_upi_app"),
        ("parties", "0008_add_ordering_and_search_indexes_to_party"),
        ("platform", "0009_normalise_user_mobiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("due_on", models.DateField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp_manual", "WhatsApp"),
                            ("sms_manual", "SMS from your phone"),
                            ("sms", "SMS"),
                            ("whatsapp_api", "WhatsApp (automatic)"),
                            ("call", "Call"),
                            ("in_app", "In app"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("auto_d1", "Day before"),
                            ("auto_d0", "Due day"),
                            ("recurring", "Recurring"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("done", "Done"),
                            ("dismissed", "Dismissed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                ("message_log_id", models.UUIDField(blank=True, null=True)),
                (
                    "snapshot_balance",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reminders",
                        to="parties.party",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "reminder",
                "verbose_name_plural": "reminders",
                "db_table": "ledger_reminder",
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "due_on"], name="ix_reminder_status_due"
                    ),
                    models.Index(fields=["party", "-created_at"], name="ix_reminder_party_recent"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind__in", ["auto_d1", "auto_d0"])),
                        fields=("party", "due_on", "kind"),
                        name="uq_reminder_auto_per_day",
                    )
                ],
            },
        ),
    ]
