# Generated by Django 5.2.6 on 2026-09-24 15:26

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_attachment"),
        ("platform", "0010_session_last_used_audit_actor_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Export",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_name", models.CharField(max_length=64)),
                ("resource", models.CharField(blank=True, max_length=32, null=True)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("format", models.CharField(default="csv", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="files.attachment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "export",
                "verbose_name_plural": "exports",
                "db_table": "reports_export",
                "indexes": [
                    models.Index(fields=["tenant", "-created_at"], name="ix_export_tenant_created"),
                    models.Index(fields=["status", "expires_at"], name="ix_export_status_expires"),
                ],
            },
        ),
    ]
