# Generated by Django 5.2.6 on 2026-09-28 08:33

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0011_support_access_impersonation"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_name", models.CharField(max_length=64)),
                ("as_of", models.DateField()),
                ("params_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("computed_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "report snapshot",
                "verbose_name_plural": "report snapshots",
                "db_table": "reports_snapshot",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "report_name", "as_of", "params_hash"),
                        name="uq_reports_snapshot",
                    )
                ],
            },
        ),
    ]
