// GENERATED by scripts/split-locales.mjs from locales/catalogues.json — do not
// edit by hand; change the table and re-run the script.
import { defineCatalogue } from 'src/i18n/catalogueRegistry';

import en from 'locales/catalogues/calendar.en.json';

/**
 * The `calendar` catalogue. Importing this module is what
 * loads it: a screen that renders these words imports it, and the words
 * arrive with that screen's chunk. See `src/i18n/catalogueRegistry.ts`.
 */
export const calendarCatalogue = defineCatalogue({
  name: 'calendar',
  en,
  loadHi: () => import('locales/catalogues/calendar.hi.json').then((module) => module.default),
});
