// GENERATED by scripts/split-locales.mjs from locales/catalogues.json — do not
// edit by hand; change the table and re-run the script.
import { defineCatalogue } from 'src/i18n/catalogueRegistry';

import en from 'locales/en.json';

/**
 * The SHELL catalogue: what every route can render. Imported by
 * `useMessages`, so it is in the chunk `app/layout` loads. See
 * `src/i18n/catalogueRegistry.ts`.
 */
export const shellCatalogue = defineCatalogue({
  name: 'shell',
  en,
  loadHi: () => import('locales/hi.json').then((module) => module.default),
});
