# Generated by Django 5.2.6 on 2026-09-24 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parties", "0008_add_ordering_and_search_indexes_to_party"),
        ("platform", "0011_support_access_impersonation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=32)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Received"), ("out", "Paid out")], max_length=3
                    ),
                ),
                ("payment_date", models.DateField()),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
                ("mode_breakup", models.JSONField()),
                (
                    "primary_mode",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("upi", "UPI"),
                            ("bank", "Bank"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("recorded", "Recorded"), ("void", "Void")],
                        default="recorded",
                        max_length=10,
                    ),
                ),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=160, null=True)),
                (
                    "unallocated_amount",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments",
                        to="parties.party",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "db_table": "payments_payment",
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_type", models.CharField(max_length=32)),
                ("document_id", models.UUIDField()),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="allocations",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment allocation",
                "verbose_name_plural": "payment allocations",
                "db_table": "payments_allocation",
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "-payment_date", "-created_at"], name="ix_payment_tenant_date"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                condition=models.Q(("party__isnull", False)),
                fields=["tenant", "party", "-payment_date"],
                name="ix_payment_tenant_party",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "direction", "status"], name="ix_payment_direction_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "number"), name="uq_payment_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ck_payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unallocated_amount__gte", 0), ("unallocated_amount__lte", models.F("amount"))
                ),
                name="ck_payment_unallocated_within_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "recorded"),
                    models.Q(("status", "void"), ("void_reason__isnull", False)),
                    _connector="OR",
                ),
                name="ck_payment_void_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("direction", "in"), ("party__isnull", False), _connector="OR"),
                name="ck_payment_out_has_party",
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["tenant", "document_type", "document_id"], name="ix_allocation_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.UniqueConstraint(
                fields=("payment", "document_type", "document_id"), name="uq_allocation_target"
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ck_allocation_amount_positive"
            ),
        ),
    ]
