"""Held deposits — `payments_held_deposit` and `payments_deposit_application` (A4b, ADR-044,
contracts §1.4, FRD 00 PLT-X02).

A deposit is a document of the `deposit` ledger bucket: `held = received − applied − refunded`,
with CHECKs that it is never negative and never receives more than expected. An application is
the pair of `adjustment` payments (OUT of the deposit, IN to the charges) that settle what the
party owes from what is held; it records both, so a void reverses both. `adjustment` joins
`payments_payment.primary_mode`'s choices (no money moves), and `ck_payment_adjustment_is_whole`
keeps an adjustment payment to a single `mode_breakup` line of that mode. Both tables are new and
tenant-scoped; nothing existing is rewritten.
"""

# Generated by Django 5.2.6 on 2026-09-29 22:30

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models

import apps.common.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0009_party_bucket_caches"),
        ("payments", "0003_payment_bucket"),
        ("platform", "0012_sequence_perpetual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
                ("reason", models.CharField(max_length=160)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "deposit application",
                "verbose_name_plural": "deposit applications",
                "db_table": "payments_deposit_application",
            },
        ),
        migrations.CreateModel(
            name="HeldDeposit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("module", models.CharField(max_length=32)),
                ("subject_type", models.CharField(max_length=48)),
                ("subject_id", models.UUIDField()),
                ("purpose", models.CharField(max_length=60)),
                (
                    "expected_amount",
                    apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14),
                ),
                (
                    "received_amount",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "applied_amount",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "refunded_amount",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "held_amount",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expected", "Expected"),
                            ("held", "Held"),
                            ("released", "Released"),
                        ],
                        default="expected",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("version", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "held deposit",
                "verbose_name_plural": "held deposits",
                "db_table": "payments_held_deposit",
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="primary_mode",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("upi", "UPI"),
                    ("bank", "Bank"),
                    ("cheque", "Cheque"),
                    ("card", "Card"),
                    ("other", "Other"),
                    ("adjustment", "Adjusted, no money moved"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("primary_mode", "adjustment"), _negated=True),
                    django.db.models.lookups.Exact(
                        models.Func(
                            models.F("mode_breakup"),
                            function="jsonb_array_length",
                            output_field=models.IntegerField(),
                        ),
                        1,
                    ),
                    _connector="OR",
                ),
                name="ck_payment_adjustment_is_whole",
            ),
        ),
        migrations.AddField(
            model_name="depositapplication",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="depositapplication",
            name="refund_payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="deposit_refund_application",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="depositapplication",
            name="settle_payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="deposit_settle_application",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="depositapplication",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="+", to="platform.tenant"
            ),
        ),
        migrations.AddField(
            model_name="helddeposit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="helddeposit",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="held_deposits",
                to="parties.party",
            ),
        ),
        migrations.AddField(
            model_name="helddeposit",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="+", to="platform.tenant"
            ),
        ),
        migrations.AddField(
            model_name="depositapplication",
            name="deposit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="applications",
                to="payments.helddeposit",
            ),
        ),
        migrations.AddIndex(
            model_name="helddeposit",
            index=models.Index(fields=["tenant", "party", "status"], name="ix_deposit_party"),
        ),
        migrations.AddIndex(
            model_name="helddeposit",
            index=models.Index(
                fields=["tenant", "subject_type", "subject_id"], name="ix_deposit_subject"
            ),
        ),
        migrations.AddIndex(
            model_name="helddeposit",
            index=models.Index(
                condition=models.Q(("status", "released"), _negated=True),
                fields=["tenant", "module"],
                name="ix_deposit_module_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="helddeposit",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_amount__gt", 0)), name="ck_deposit_expected_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="helddeposit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "held_amount",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("received_amount"), "-", models.F("applied_amount")
                            ),
                            "-",
                            models.F("refunded_amount"),
                        ),
                    )
                ),
                name="ck_deposit_held_formula",
            ),
        ),
        migrations.AddConstraint(
            model_name="helddeposit",
            constraint=models.CheckConstraint(
                condition=models.Q(("held_amount__gte", 0)), name="ck_deposit_held_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="helddeposit",
            constraint=models.CheckConstraint(
                condition=models.Q(("received_amount__lte", models.F("expected_amount"))),
                name="ck_deposit_received_within_expected",
            ),
        ),
        migrations.AddConstraint(
            model_name="helddeposit",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["expected", "held", "released"])),
                name="ck_deposit_status",
            ),
        ),
        migrations.AddIndex(
            model_name="depositapplication",
            index=models.Index(fields=["tenant", "deposit"], name="ix_deposit_application_deposit"),
        ),
        migrations.AddConstraint(
            model_name="depositapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ck_deposit_application_positive"
            ),
        ),
    ]
