# Generated by Django 5.2.6 on 2026-09-24 20:42

import apps.common.db.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0008_add_ordering_and_search_indexes_to_party"),
        ("platform", "0011_support_access_impersonation"),
        ("sales", "0001_add_sales_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesCreditApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
            ],
            options={
                "verbose_name": "credit application",
                "verbose_name_plural": "credit applications",
                "db_table": "sales_credit_application",
            },
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="against",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="credit_notes",
                to="sales.salesdocument",
            ),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="converted_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sales.salesdocument",
            ),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="converted_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sales.salesdocument",
            ),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesdocumentline",
            name="against_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="return_lines",
                to="sales.salesdocumentline",
            ),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="kind",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice"),
                    ("bill_of_supply", "Bill of supply"),
                    ("estimate", "Estimate"),
                    ("credit_note", "Credit note"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("issued", "Issued"),
                    ("partially_paid", "Partially paid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("void", "Void"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("converted", "Converted"),
                    ("applied", "Applied"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="salesdocument",
            index=models.Index(
                condition=models.Q(("against__isnull", False)),
                fields=["tenant", "against"],
                name="ix_sales_doc_against",
            ),
        ),
        migrations.AddField(
            model_name="salescreditapplication",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salescreditapplication",
            name="credit_note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="applications",
                to="sales.salesdocument",
            ),
        ),
        migrations.AddField(
            model_name="salescreditapplication",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="credit_applications",
                to="sales.salesdocument",
            ),
        ),
        migrations.AddField(
            model_name="salescreditapplication",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="+", to="platform.tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="salescreditapplication",
            index=models.Index(fields=["tenant", "invoice"], name="ix_sales_credit_app_invoice"),
        ),
        migrations.AddConstraint(
            model_name="salescreditapplication",
            constraint=models.UniqueConstraint(
                fields=("credit_note", "invoice"), name="uq_sales_credit_application_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="salescreditapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ck_sales_credit_application_positive"
            ),
        ),
    ]
