"""The dues engine's nine tables, once (FRD 00 DUE-01 §5, contracts §2.1, R16, R17).

Depends on the Wave B core heads (plan §3): the engine posts ledger lines,
issues documents through the port (sales' origin columns), settles through
payments and reads the closed-day calendar, so it migrates after all of them.
"""

# Generated by Django 5.2.6 on 2026-10-01 16:20

import apps.common.db.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0007_reminder_source"),
        ("parties", "0010_party_relation"),
        ("payments", "0004_held_deposit"),
        ("sales", "0005_document_origin"),
        ("platform", "0013_closed_day"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DuesPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("freq", models.CharField(max_length=8)),
                ("interval", models.SmallIntegerField(default=1)),
                ("by_weekday", models.SmallIntegerField(default=0)),
                ("by_month_day", models.SmallIntegerField(blank=True, null=True)),
                ("anchor", models.DateField()),
                ("count", models.IntegerField(blank=True, null=True)),
                ("until", models.DateField(blank=True, null=True)),
                (
                    "explicit_dates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(), blank=True, default=list, size=None
                    ),
                ),
                ("module", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=80)),
                ("mode", models.CharField(max_length=12)),
                ("posting", models.CharField(max_length=8)),
                ("amount_rule", models.CharField(max_length=12)),
                (
                    "amount",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "total",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "split_weights",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DecimalField(decimal_places=4, max_digits=9),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("join_policy", models.CharField(default="full", max_length=14)),
                ("leave_policy", models.CharField(default="no_refund", max_length=12)),
                ("grace_days", models.SmallIntegerField(default=0)),
                ("penalty_kind", models.CharField(default="none", max_length=16)),
                (
                    "penalty_value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "penalty_cap",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("pause_max_days", models.SmallIntegerField(blank=True, null=True)),
                ("pause_min_days", models.SmallIntegerField(blank=True, null=True)),
                ("pause_max_count", models.SmallIntegerField(blank=True, null=True)),
                ("hsn_sac", models.CharField(blank=True, max_length=8, null=True)),
                ("tax_code", models.CharField(blank=True, max_length=16, null=True)),
                ("tax_inclusive", models.BooleanField(default=False)),
                ("rounding_rule", models.CharField(default="rupee", max_length=8)),
                ("allocation_order", models.CharField(default="oldest_first", max_length=12)),
                ("auto_apply_advance", models.BooleanField(default=True)),
                ("closed_day_rule", models.CharField(default="ignore", max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "dues_plan",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuesPlanHead",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seq", models.SmallIntegerField()),
                ("label", models.CharField(max_length=60)),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heads",
                        to="dues.duesplan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "dues_plan_head",
                "ordering": ("seq",),
            },
        ),
        migrations.CreateModel(
            name="DuesSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("freq", models.CharField(max_length=8)),
                ("interval", models.SmallIntegerField(default=1)),
                ("by_weekday", models.SmallIntegerField(default=0)),
                ("by_month_day", models.SmallIntegerField(blank=True, null=True)),
                ("anchor", models.DateField()),
                ("count", models.IntegerField(blank=True, null=True)),
                ("until", models.DateField(blank=True, null=True)),
                (
                    "explicit_dates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(), blank=True, default=list, size=None
                    ),
                ),
                ("module", models.CharField(max_length=32)),
                ("mode", models.CharField(max_length=12)),
                ("posting", models.CharField(max_length=8)),
                (
                    "amount",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "total",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("grace_days", models.SmallIntegerField(default=0)),
                ("penalty_kind", models.CharField(default="none", max_length=16)),
                (
                    "penalty_value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "penalty_cap",
                    apps.common.db.fields.MoneyField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("allocation_order", models.CharField(default="oldest_first", max_length=12)),
                ("closed_day_rule", models.CharField(default="ignore", max_length=8)),
                ("rounding_rule", models.CharField(default="rupee", max_length=8)),
                ("terms", models.JSONField(blank=True, default=dict)),
                ("subject_type", models.CharField(max_length=48)),
                ("subject_id", models.UUIDField()),
                ("start_on", models.DateField()),
                ("end_on", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=10)),
                ("ended_reason", models.CharField(blank=True, default="", max_length=160)),
                ("materialised_until", models.DateField()),
                ("version", models.IntegerField(default=1)),
                (
                    "beneficiary_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="parties.party",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="parties.party",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="schedules",
                        to="dues.duesplan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "dues_schedule",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuesPause",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_on", models.DateField()),
                ("to_on", models.DateField()),
                ("effect", models.CharField(max_length=5)),
                ("reason", models.CharField(max_length=160)),
                ("resumed_on", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="pauses",
                        to="dues.duesschedule",
                    ),
                ),
            ],
            options={
                "db_table": "dues_pause",
            },
        ),
        migrations.CreateModel(
            name="DuesDue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("module", models.CharField(max_length=32)),
                ("seq", models.IntegerField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("period_label", models.CharField(max_length=40)),
                ("due_on", models.DateField()),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
                ("status", models.CharField(default="scheduled", max_length=10)),
                (
                    "settled_amount",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "waived_amount",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "penalty_amount",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                ("penalty_exempt_days", models.SmallIntegerField(default=0)),
                ("paid_on", models.DateField(blank=True, null=True)),
                ("document_id", models.UUIDField(blank=True, null=True)),
                ("posted_entry_id", models.UUIDField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, default="", max_length=160)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="parties.party",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dues",
                        to="dues.duesschedule",
                    ),
                ),
            ],
            options={
                "db_table": "dues_due",
            },
        ),
        migrations.CreateModel(
            name="DuesScheduleHead",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seq", models.SmallIntegerField()),
                ("label", models.CharField(max_length=60)),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heads",
                        to="dues.duesschedule",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "dues_schedule_head",
                "ordering": ("seq",),
            },
        ),
        migrations.CreateModel(
            name="DuesSettlement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_id", models.UUIDField()),
                ("component", models.CharField(max_length=10)),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "due",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="settlements",
                        to="dues.duesdue",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "dues_settlement",
            },
        ),
        migrations.CreateModel(
            name="DuesAdjustment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=10)),
                ("component", models.CharField(blank=True, max_length=10, null=True)),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
                ("reason", models.CharField(max_length=160)),
                ("posted_entry_id", models.UUIDField(blank=True, null=True)),
                ("document_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="dues.duesadjustment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
                (
                    "due",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="adjustments",
                        to="dues.duesdue",
                    ),
                ),
            ],
            options={
                "db_table": "dues_adjustment",
                "indexes": [models.Index(fields=["tenant", "due"], name="ix_dues_adjustment_due")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("amount__gt", 0), ("kind", "penalty")),
                            models.Q(
                                ("amount__lt", 0), ("kind__in", ["waiver", "discount", "proration"])
                            ),
                            _connector="OR",
                        ),
                        name="ck_dues_adjustment_sign",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("component__isnull", True),
                            ("component__in", ["principal", "interest", "fee", "charge"]),
                            _connector="OR",
                        ),
                        name="ck_dues_adjustment_component",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DuesDueComponent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.common.db.fields.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("component", models.CharField(max_length=10)),
                ("amount", apps.common.db.fields.MoneyField(decimal_places=2, max_digits=14)),
                (
                    "settled",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "waived",
                    apps.common.db.fields.MoneyField(decimal_places=2, default=0, max_digits=14),
                ),
                ("posted_entry_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "due",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="components",
                        to="dues.duesdue",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="platform.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "dues_due_component",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("due", "component"), name="uq_dues_due_component"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount__gte", 0),
                            ("settled__gte", 0),
                            ("waived__gte", 0),
                            (
                                "settled__lte",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("amount"), "-", models.F("waived")
                                ),
                            ),
                        ),
                        name="ck_dues_due_component_money",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("component__in", ["principal", "interest", "fee", "charge"])
                        ),
                        name="ck_dues_due_component_kind",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="duesplan",
            index=models.Index(
                fields=["tenant", "module", "is_active"], name="ix_dues_plan_module"
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("freq__in", ("once", "daily", "weekly", "monthly", "yearly"))),
                name="dues_duesplan_recurrence_freq_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval__gte", 1), ("interval__lte", 366)),
                name="dues_duesplan_recurrence_interval_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("by_weekday__gte", 0), ("by_weekday__lte", 127)),
                name="dues_duesplan_recurrence_by_weekday_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("by_month_day__isnull", True),
                    ("by_month_day", -1),
                    models.Q(("by_month_day__gte", 1), ("by_month_day__lte", 31)),
                    _connector="OR",
                ),
                name="dues_duesplan_recurrence_by_month_day_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("count__isnull", True),
                    models.Q(("count__gte", 1), ("count__lte", 1000)),
                    _connector="OR",
                ),
                name="dues_duesplan_recurrence_count_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("until__isnull", True), ("until__gte", models.F("anchor")), _connector="OR"
                ),
                name="dues_duesplan_recurrence_until_after_anchor",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mode", "charge"), ("posting__in", ["document", "ledger"])),
                    models.Q(("mode", "expectation"), ("posting", "none")),
                    _connector="OR",
                ),
                name="ck_dues_plan_mode_posting",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("hsn_sac__isnull", True), ("tax_code__isnull", True)),
                    ("posting", "document"),
                    _connector="OR",
                ),
                name="ck_dues_plan_taxable_is_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("amount_rule", "fixed"), _negated=True),
                    ("amount__isnull", False),
                    _connector="OR",
                ),
                name="ck_dues_plan_fixed_has_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("amount_rule", "total_split"), _negated=True),
                    ("total__isnull", False),
                    _connector="OR",
                ),
                name="ck_dues_plan_split_has_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("penalty_kind", "none"), ("penalty_value__isnull", True)),
                    models.Q(
                        models.Q(("penalty_kind", "none"), _negated=True),
                        ("penalty_value__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_dues_plan_penalty_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("amount__isnull", True), ("amount__gte", 0), _connector="OR"),
                    models.Q(
                        ("penalty_cap__isnull", True), ("penalty_cap__gte", 0), _connector="OR"
                    ),
                    models.Q(
                        ("penalty_value__isnull", True), ("penalty_value__gte", 0), _connector="OR"
                    ),
                ),
                name="ck_dues_plan_money_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__isnull", True), ("total__gt", 0), _connector="OR"),
                name="ck_dues_plan_total_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("grace_days__gte", 0), ("grace_days__lte", 365)),
                name="ck_dues_plan_grace",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["charge", "expectation"])),
                name="ck_dues_plan_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("posting__in", ["document", "ledger", "none"])),
                name="ck_dues_plan_posting",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_rule__in", ["fixed", "total_split", "supplied"])),
                name="ck_dues_plan_amount_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "join_policy__in",
                        ["full", "by_days", "half_rule", "next_period", "align_to_join"],
                    )
                ),
                name="ck_dues_plan_join_policy",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("leave_policy__in", ["no_refund", "by_days", "by_sessions", "custom"])
                ),
                name="ck_dues_plan_leave_policy",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "penalty_kind__in",
                        ["none", "flat_once", "percent_once", "per_day", "simple_interest"],
                    )
                ),
                name="ck_dues_plan_penalty_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocation_order__in", ["oldest_first", "fees_first", "fees_last"])
                ),
                name="ck_dues_plan_allocation_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("closed_day_rule__in", ["move", "skip", "ignore"])),
                name="ck_dues_plan_closed_day_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("rounding_rule__in", ("paise", "rupee", "rupee_up", "ten_up"))),
                name="ck_dues_plan_rounding_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplan",
            constraint=models.UniqueConstraint(
                models.F("tenant"),
                models.F("module"),
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("is_active", True)),
                name="uq_dues_plan_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplanhead",
            constraint=models.UniqueConstraint(
                fields=("plan", "seq"), name="uq_dues_plan_head_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="duesplanhead",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="ck_dues_plan_head_amount"
            ),
        ),
        migrations.AddIndex(
            model_name="duesschedule",
            index=models.Index(fields=["tenant", "party", "status"], name="ix_dues_schedule_party"),
        ),
        migrations.AddIndex(
            model_name="duesschedule",
            index=models.Index(
                fields=["tenant", "module", "status"], name="ix_dues_schedule_module"
            ),
        ),
        migrations.AddIndex(
            model_name="duesschedule",
            index=models.Index(
                condition=models.Q(("status__in", ("active", "paused"))),
                fields=["tenant", "materialised_until"],
                name="ix_dues_schedule_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("freq__in", ("once", "daily", "weekly", "monthly", "yearly"))),
                name="dues_duesschedule_recurrence_freq_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval__gte", 1), ("interval__lte", 366)),
                name="dues_duesschedule_recurrence_interval_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("by_weekday__gte", 0), ("by_weekday__lte", 127)),
                name="dues_duesschedule_recurrence_by_weekday_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("by_month_day__isnull", True),
                    ("by_month_day", -1),
                    models.Q(("by_month_day__gte", 1), ("by_month_day__lte", 31)),
                    _connector="OR",
                ),
                name="dues_duesschedule_recurrence_by_month_day_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("count__isnull", True),
                    models.Q(("count__gte", 1), ("count__lte", 1000)),
                    _connector="OR",
                ),
                name="dues_duesschedule_recurrence_count_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("until__isnull", True), ("until__gte", models.F("anchor")), _connector="OR"
                ),
                name="dues_duesschedule_recurrence_until_after_anchor",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("active", "paused"))),
                fields=("tenant", "subject_type", "subject_id"),
                name="uq_dues_schedule_live_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_on__isnull", True), ("end_on__gt", models.F("start_on")), _connector="OR"
                ),
                name="ck_dues_schedule_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mode", "charge"), ("posting__in", ["document", "ledger"])),
                    models.Q(("mode", "expectation"), ("posting", "none")),
                    _connector="OR",
                ),
                name="ck_dues_schedule_mode_posting",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "paused", "ended", "cancelled"])),
                name="ck_dues_schedule_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("amount__isnull", True), ("amount__gte", 0), _connector="OR"),
                    models.Q(
                        ("penalty_cap__isnull", True), ("penalty_cap__gte", 0), _connector="OR"
                    ),
                    models.Q(
                        ("penalty_value__isnull", True), ("penalty_value__gte", 0), _connector="OR"
                    ),
                    models.Q(("total__isnull", True), ("total__gt", 0), _connector="OR"),
                ),
                name="ck_dues_schedule_money",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "penalty_kind__in",
                        ["none", "flat_once", "percent_once", "per_day", "simple_interest"],
                    )
                ),
                name="ck_dues_schedule_penalty_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocation_order__in", ["oldest_first", "fees_first", "fees_last"])
                ),
                name="ck_dues_schedule_allocation_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("closed_day_rule__in", ["move", "skip", "ignore"])),
                name="ck_dues_schedule_closed_day_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("rounding_rule__in", ("paise", "rupee", "rupee_up", "ten_up"))),
                name="ck_dues_schedule_rounding_rule",
            ),
        ),
        migrations.AddIndex(
            model_name="duespause",
            index=models.Index(
                fields=["tenant", "schedule", "from_on"], name="ix_dues_pause_schedule"
            ),
        ),
        migrations.AddConstraint(
            model_name="duespause",
            constraint=models.CheckConstraint(
                condition=models.Q(("to_on__gte", models.F("from_on"))), name="ck_dues_pause_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="duespause",
            constraint=models.CheckConstraint(
                condition=models.Q(("effect__in", ["shift", "skip"])), name="ck_dues_pause_effect"
            ),
        ),
        migrations.AddIndex(
            model_name="duesdue",
            index=models.Index(fields=["tenant", "status", "due_on"], name="ix_dues_due_status"),
        ),
        migrations.AddIndex(
            model_name="duesdue",
            index=models.Index(fields=["tenant", "party", "due_on"], name="ix_dues_due_party"),
        ),
        migrations.AddIndex(
            model_name="duesdue",
            index=models.Index(
                fields=["tenant", "module", "status", "due_on"], name="ix_dues_due_module"
            ),
        ),
        migrations.AddIndex(
            model_name="duesdue",
            index=models.Index(
                condition=models.Q(("status__in", ("due", "overdue"))),
                fields=["tenant", "party", "due_on", "seq"],
                name="ix_dues_due_open_party",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesdue",
            constraint=models.UniqueConstraint(fields=("schedule", "seq"), name="uq_dues_due_seq"),
        ),
        migrations.AddConstraint(
            model_name="duesdue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount__gte", 0),
                    ("penalty_amount__gte", 0),
                    ("penalty_exempt_days__gte", 0),
                    ("settled_amount__gte", 0),
                    ("waived_amount__gte", 0),
                ),
                name="ck_dues_due_money_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesdue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "settled_amount__lte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("amount"), "+", models.F("penalty_amount")
                            ),
                            "-",
                            models.F("waived_amount"),
                        ),
                    )
                ),
                name="ck_dues_due_settled_within_owed",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesdue",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gt", models.F("period_start"))),
                name="ck_dues_due_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesdue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("document_id__isnull", False),
                    ("posted_entry_id__isnull", False),
                    _negated=True,
                ),
                name="ck_dues_due_one_posting",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesdue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "paid"), _negated=True),
                    ("paid_on__isnull", False),
                    _connector="OR",
                ),
                name="ck_dues_due_paid_has_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesdue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["scheduled", "due", "overdue", "paid", "skipped", "cancelled"])
                ),
                name="ck_dues_due_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedulehead",
            constraint=models.UniqueConstraint(
                fields=("schedule", "seq"), name="uq_dues_schedule_head_seq"
            ),
        ),
        migrations.AddConstraint(
            model_name="duesschedulehead",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="ck_dues_schedule_head_amount"
            ),
        ),
        migrations.AddIndex(
            model_name="duessettlement",
            index=models.Index(fields=["tenant", "due"], name="ix_dues_settlement_due"),
        ),
        migrations.AddConstraint(
            model_name="duessettlement",
            constraint=models.UniqueConstraint(
                fields=("payment_id", "due", "component"), name="uq_dues_settlement"
            ),
        ),
        migrations.AddConstraint(
            model_name="duessettlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ck_dues_settlement_amount"
            ),
        ),
        migrations.AddConstraint(
            model_name="duessettlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("component__in", ["principal", "interest", "fee", "charge"])),
                name="ck_dues_settlement_component",
            ),
        ),
    ]
